---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-2
  tasks:
    - name: launch instance
      ec2:
        region: "{{ region }}"
        key_name: danylo-key-pair-useast
        instance_type: t2.micro
        image: ami-05d72852800cbf29e
        wait: yes
        group: SG-webserver-useast
      register: ec2

    - name: associate new EIP for the instance
      ec2_eip:
        region: "{{ region }}"
        device_id : "{{ item.id }}"
        in_vpc: yes
      with_items: "{{ ec2.instances }}"
