---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
  #your region
    region: us-east-2
  tasks:
    - name: EC2 basic provisioning
      ec2:
        region: "{{ region }}"
        key_name: danylo-key-pair-useast
        instance_type: t2.micro
        image: ami-05d72852800cbf29e
        wait: yes
        group: SG-webserver-useast
        instance_tags:
          group: webserver
        exact_count: 2
        count_tag:
          group: webserver
