---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    #your region
    region: us-east-2
    allowed_id: 46.173.150.84/32
  tasks:
    - name: create security group
      ec2_group:
        region: "{{ region }}"
        # your security group name
        name: SG-webserver-useast
        description: security group for us-east webserver host
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ allowed_id }}"
            #allow http acces from anywhere
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cird_id: 0.0.0.0/0
